
#' Sea otter trophic cascade
#'
#' Data used to demonstrate and test trophic cascades options
#'
#' @name sea_otter
#' @docType data
#' @usage data(sea_otter)
#' @keywords data
NULL

#' Bering Sea marine ecosystem
#'
#' Data used to demonstrate and test ecosystem synthesis
#'
#' @name bering_sea
#' @docType data
#' @usage data(bering_sea)
#' @keywords data
NULL

#' @title Isle Royale wolf and moose
#'
#' @description
#' Data used to demonstrate and test cross-lagged (vector autoregressive) models
#'
#' @details
#' Data extracted from file "Data_wolves_moose_Isle_Royale_June2019.csv" available at
#' \url{https://isleroyalewolf.org/data/data/home.html} and obtained 2023-06-23.
#' Reproduced with permission from John Vucetich, and generated by the
#' Wolves and Moose of Isle Royale project.
#'
#' @references
#' Vucetich, JA and Peterson RO. 2012. The population biology of Isle Royale wolves and moose: an overview. \url{www.isleroyalewolf.org}
#'
#' @name isle_royale
#' @docType data
#' @usage data(isle_royale)
#' @keywords data
NULL

